name: harj2
on: push

jobs:
  haaroitus:
    runs-on: ubuntu-latest
    steps:
      - name: production
        if: ${{github.ref_name == 'main'}}
        run: echo "Push into production"
      - name: other
        if: ${{github.ref_name != 'main'}}
        run: echo "Branch name is ${{github.ref_name}}"
